- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.5.217:8080
    user: admin
    password: admin123
  loop: folders




- name: include task
  ansible.builtin.include_tasks: pipeline.yml
  loop: pipelines
   
