- name: Create a jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.5.217:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: create multi-jobs-pipeline jobs
  ansible.builtin.include_tasks: pipeline-m.yml
  loop: "{{ ci_pipelines_jobs }}"
   
- name: create single-pipeline jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipelines_jobs }}"
   
