- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.5.217:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"




- name: create pipeline jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipelines_jobs }}"
   
