- name: Check if Job exists or not - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.5.217:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes


- name: debug
  ansible.builtin.debug: 
   msg: "{{out}}"

  


- name: config files
  ansible.builtin.template: 
   src: job1.xml 
   dest: /tmp/job1.xml
  when: out.rc == 3

- name: Create a jenkins job - {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job1.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.5.217:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc == 3
