- name: config files
  ansible.builtin.template: 
   src: job.xml 
   dest: /temp/job.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/temp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.5.217:8080
    user: admin
    password: "{{jenkins_password}}"